<?php
App::uses('AppController','Controller');

class PostsController extends AppController
{
	public function beforeFilter()
	{
		parent::beforeFilter(); // TODO: Change the autogenerated stub
	}

	public function view(){
		$conditions = array();
		$data = array();
		if(!empty($this->passedArgs)){
			if(isset($this->passedArgs['Book.title'])) {
				//kiểm tra xem có tồn tại title hay không
				$title = $this->passedArgs['Book.title'];
				$conditions[] = array( 'Book.title LIKE' => "%$title%", );
				//điều kiện SQL
				$data['Book']['title'] = $title;
				//cho giá trị nhập vào mảng data
			}
			if(isset($this->passedArgs['Book.description'])) {
				$description = $this->passedArgs['Book.description'];
				$conditions[] = array( "OR" => array(
					'Book.description LIKE' => "%$description%" ) );
				$data['Book']['description'] = $description;
			}
			$this->paginate= array( 'limit' => 2, 'order' => array('id' => 'desc'), );
			$this->data = $data;
			//Giữ lại giá trị nhập vào sau khi submit
			$post = $this->paginate("Book",$conditions);
			$this->set("posts",$post);
		}
	}
	function search() {
		$url['action'] = 'view';
		foreach ($this->data as $key=>$value){
			foreach ($value as $key2=>$value2){
				$url[$key.'.'.$key2]=$value2;
			}
		}
		// chuyển hướng sang action view
		$this->redirect($url, null, true);
	}

	public function add()
	{
//		if (isset($this->request->is('post'))){
//
//		}
	}
}
